In [2]:
from bs4 import BeautifulSoup

# Load your HTML file
with open('players.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Parse HTML content
soup = BeautifulSoup(content, 'html.parser')

# Initialize lists to store data
players = []
categories = []
prices = []

# Find the section that contains player data
for player_row in soup.find_all('div', class_='AUipl_tbl-tr'):  # Replace with actual class
    # Extract player name
    player_name = player_row.find('div', class_='AUipl_tbl-nm AUipl_tbl-PlIc').text.strip()  # Replace with actual class
    players.append(player_name)

    # Extract category
    player_category = player_row.find('div', class_='AUipl_tbl-MTy').text.strip()  # Replace with actual class
    categories.append(player_category)

    # Extract price
    player_price = player_row.find('div', class_='AUipl_tx-CtRt').text.strip()  # Replace with actual class
    prices.append(player_price)

# Print the extracted data
for player, category, price in zip(players, categories, prices):
    print(f'Player: {player}, Category: {category}, Price: {price}')

In [4]:
import csv
from bs4 import BeautifulSoup

# Load HTML content
with open('players.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(content, 'html.parser')

# Open a CSV file to write the extracted data
with open('ipl_players.csv', 'w', newline='', encoding='utf-8') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['Player Name', 'Category', 'Price (₹ Cr.)'])  # Write CSV header

    # Find all the relevant table rows containing player info
    for row in soup.find_all('tr', class_='AUipl_tbl-tr'):
        # Extract the player's name
        player_name_tag = row.find('a')
        player_name = player_name_tag.text.strip() if player_name_tag else 'N/A'

        # Extract the category
        category_tag = row.find('td', class_='AUipl_tx-ctlt')
        category = category_tag.text.strip() if category_tag else 'N/A'

        # Extract the price
        price_tag = row.find('td', class_='AUipl_tx-act')
        price = price_tag.text.strip() if price_tag else 'N/A'

        csvwriter.writerow([player_name, category, price])  # Write to CSV file

print("Data has been successfully written to 'ipl_players.csv'.")

Data has been successfully written to 'ipl_players.csv'.

In [5]:
import csv

# Read the CSV file and filter out rows with "N/A"
with open('ipl_players.csv', 'r', encoding='utf-8') as infile, open('filtered_ipl_players.csv', 'w', newline='', encoding='utf-8') as outfile:
    csvreader = csv.reader(infile)
    csvwriter = csv.writer(outfile)
    
    # Write the header to the new CSV file
    header = next(csvreader)
    csvwriter.writerow(header)
    
    # Filter and write rows that do not contain "N/A"
    for row in csvreader:
        if "N/A" not in row:
            csvwriter.writerow(row)

print("Filtered data has been successfully written to 'filtered_ipl_players.csv'.")

Filtered data has been successfully written to 'filtered_ipl_players.csv'.

In [10]:
unsold_players = """
1	Adil Rashid	Bowler 	
2.00
2	Josh Hazlewood	Bowler 	
2.00
3	Josh Inglis	Wicket-Keeper 	
2.00
4	Rassie van der Dussen	Batter 	
2.00
5	Steven Smith	Batter 	
2.00
6	Colin Munro	Batter 	
1.50
7	James Neesham	All-Rounder 	
1.50
8	Phil Salt	Wicket-Keeper 	
1.50
9	Tymal Mills	Bowler 	
1.50
10	Adam Milne	Bowler 	
1.00
11	Kyle Jamieson	Bowler 	
1.00
12	Michael Bracewell	All-Rounder 	
1.00
13	Finn Allen	Batter 	
0.75
14	Ish Sodhi	Bowler 	
0.75
15	Keemo Paul	All-Rounder 	
0.75
16	Lance Morris	Bowler 	
0.75
17	Matt Henry	Bowler 	
0.75
18	Akeal Hosein	Bowler 	
0.50
19	Ben Dwarshuis	Bowler 	
0.50
20	Dushmantha Chameera	Bowler 	
0.50
21	Karun Nair	Batter 	
0.50
22	Kusal Mendis	Wicket-Keeper 	
0.50
23	Luke Wood	Bowler 	
0.50
24	Odean Smith	All-Rounder 	
0.50
25	Qais Ahmad	All-Rounder 	
0.50
26	Sandeep Warrier	Bowler 	
0.50
27	Tabraiz Shamsi	Bowler 	
0.50
28	Waqar Salamkheil	Bowler 	
0.50
29	Kamlesh Nagarkoti	All-Rounder 	
0.30
30	Abhilash Shetty	Bowler 	
0.20
31	Ajitesh G	Wicket-Keeper 	
0.20
32	Amandeep Khare	Batter 	
0.20
33	Atit Sheth	All-Rounder 	
0.20
34	Bipin Saurabh	Wicket-Keeper 	
0.20
35	Gourav Choudhary	Wicket-Keeper 	
0.20
36	Gurjapneet Singh	Bowler 	
0.20
37	Harsh Dubey	All-Rounder 	
0.20
38	Himmat Singh	Batter 	
0.20
39	Hrithik Shokeen	All-Rounder 	
0.20
40	Ishan Porel	Bowler 	
0.20
41	KM Asif	Bowler 	
0.20
42	Krishnan Shrijith	Wicket-Keeper 	
0.20
43	Kuldip Yadav	Bowler 	
0.20
44	Manan Vohra	Batter 	
0.20
45	Mohammed Kaif	Bowler 	
0.20
46	Murugan Ashwin	Bowler 	
0.20
47	Pradosh Ranjan Paul	All-Rounder 	
0.20
48	Prithvi Raj	Bowler 	
0.20
49	Priyansh Arya	Batter 	
0.20
50	Pulkit Narang	Bowler 	
0.20
51	Raj Bawa	All-Rounder 	
0.20
52	Rithik Easwaran	Batter 	
0.20
53	Rohan Kunnummal	Batter 	
0.20
54	Rohit Rayudu	All-Rounder 	
0.20
55	Sarfaraz Khan	All-Rounder 	
0.20
56	Saurav Chauhan	Batter 	
0.20
57	Shashank Singh	Batter 	
0.20
58	Shiva Singh	Bowler 	
0.20
59	Shubham Agarwal	Bowler 	
0.20
60	Sumeet Verma	Batter 	
0.20
61	Tanush Kotian	All-Rounder 	
0.20
62	Urvil Patel	Wicket-Keeper 	
0.20
63	Vishnu Solanki	Wicket-Keeper 	
0.20
64	Vivrant Sharma	All-Rounder 	
0.20

"""

# Split the unsold players data into individual lines
unsold_players_list = unsold_players.strip().split('\n')

# Create a csv file to write the unsold players data
with open('unsold_players.csv', 'w', newline='', encoding='utf-8') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['S.No.', 'Player Name', 'Category', 'Price (₹ Cr.)'])  # Write CSV header

    for line in unsold_players_list:
        # Split each line by tabs to extract the data
        data = line.split('\t')
        csvwriter.writerow(data)

In [13]:
import pandas as pd

# Load the CSV file while keeping lines that have missing values in other columns
data = pd.read_csv('unsold_players.csv', header=0, skip_blank_lines=False)

# Create an empty list to store cleaned rows
cleaned_data = []

# Iterate through the rows
for i in range(len(data)):
    # If the 'Player Name' column is not NaN, it's a proper row with player details
    if pd.notna(data.loc[i, 'Player Name']):
        player_row = data.loc[i]  # Save the current player row
        
        # If the next row is the price (and the current row has an empty price), fix it
        if pd.isna(player_row['Price (₹ Cr.)']) and pd.notna(data.loc[i+1, 'Player Name']) == False:
            player_row['Price (₹ Cr.)'] = data.loc[i+1, 'Player Name']  # The next row contains the price
            cleaned_data.append(player_row)
    else:
        continue

# Convert the cleaned data list back to a DataFrame
cleaned_df = pd.DataFrame(cleaned_data)

# Drop the 'S.No.' column
cleaned_df = cleaned_df.drop(columns=['S.No.'])

# Save the cleaned data to a new CSV file
cleaned_df.to_csv('cleaned_players.csv', index=False)

print("CSV file cleaned and saved as 'cleaned_players.csv'.")

CSV file cleaned and saved as 'cleaned_players.csv'.

C:\Users\msais\AppData\Local\Temp\ipykernel_36412\2350357639.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player_row['Price (₹ Cr.)'] = data.loc[i+1, 'Player Name']  # The next row contains the price

In [16]:
import pandas as pd

df_unsold = pd.read_csv('unsold_players.csv')

df_unsold

     S.No.     Player Name        Category  Price (₹ Cr.)
0      1.0     Adil Rashid         Bowler             NaN
1      2.0             NaN             NaN            NaN
2      2.0  Josh Hazlewood         Bowler             NaN
3      2.0             NaN             NaN            NaN
4      3.0     Josh Inglis  Wicket-Keeper             NaN
..     ...             ...             ...            ...
123    0.2             NaN             NaN            NaN
124   63.0  Vishnu Solanki  Wicket-Keeper             NaN
125    0.2             NaN             NaN            NaN
126   64.0  Vivrant Sharma    All-Rounder             NaN
127    0.2             NaN             NaN            NaN

[128 rows x 4 columns]

In [17]:
# For every even row number, copy the S.No. of the next row to the Price column of the current row
for i in range(0, len(df_unsold), 2):
    df_unsold.loc[i, 'Price (₹ Cr.)'] = df_unsold.loc[i + 1, 'S.No.']  # Copy the S.No. to Price

df_unsold

     S.No.     Player Name        Category  Price (₹ Cr.)
0      1.0     Adil Rashid         Bowler             2.0
1      2.0             NaN             NaN            NaN
2      2.0  Josh Hazlewood         Bowler             2.0
3      2.0             NaN             NaN            NaN
4      3.0     Josh Inglis  Wicket-Keeper             2.0
..     ...             ...             ...            ...
123    0.2             NaN             NaN            NaN
124   63.0  Vishnu Solanki  Wicket-Keeper             0.2
125    0.2             NaN             NaN            NaN
126   64.0  Vivrant Sharma    All-Rounder             0.2
127    0.2             NaN             NaN            NaN

[128 rows x 4 columns]

In [18]:
# Drop every odd row

df_unsold = df_unsold[::2]
df_unsold

     S.No.            Player Name        Category  Price (₹ Cr.)
0      1.0            Adil Rashid         Bowler             2.0
2      2.0         Josh Hazlewood         Bowler             2.0
4      3.0            Josh Inglis  Wicket-Keeper             2.0
6      4.0  Rassie van der Dussen         Batter             2.0
8      5.0           Steven Smith         Batter             2.0
..     ...                    ...             ...            ...
118   60.0           Sumeet Verma         Batter             0.2
120   61.0          Tanush Kotian    All-Rounder             0.2
122   62.0            Urvil Patel  Wicket-Keeper             0.2
124   63.0         Vishnu Solanki  Wicket-Keeper             0.2
126   64.0         Vivrant Sharma    All-Rounder             0.2

[64 rows x 4 columns]

In [19]:
# Remove the S.No. column
df_unsold = df_unsold.drop(columns=['S.No.'])
df_unsold.to_csv('cleaned_unsold_players.csv', index=False)

In [21]:
df_unsold['Old_Team'] = 'None'

In [22]:
df_unsold.to_csv('cleaned_unsold_players.csv', index=False)

In [23]:
import csv

# The text provided
text = """

Kolkata Knight Riders
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Mitchell Starc	Bowler 	
24.75
2	Mujeeb Ur Rahman	Bowler 	
2.00
3	Sherfane Rutherford	Batter 	
1.50
4	Gus Atkinson	Bowler 	
1.00
5	Chetan Sakariya	Bowler 	
0.50
6	KS Bharat	Wicket-Keeper 	
0.50
7	Manish Pandey	Batter 	
0.50
8	Angkrish Raghuvanshi	Batter 	
0.20
9	Ramandeep Singh	All-Rounder 	
0.20
10	Sakib Hussain	Bowler 	
0.20
Sunrisers Hyderabad
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Pat Cummins	All-Rounder 	
20.50
2	Travis Head	Batter 	
6.80
3	Jaydev Unadkat	Bowler 	
1.60
4	Wanindu Hasaranga	All-Rounder 	
1.50
5	Akash Singh	Bowler 	
0.20
6	Jhatavedh Subramanyan	Bowler 	
0.20
Chennai Super Kings
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Daryl Mitchell	All-Rounder 	
14.00
2	Sameer Rizvi	Batter 	
8.40
3	Shardul Thakur	All-Rounder 	
4.00
4	Mustafizur Rahman	Bowler 	
2.00
5	Rachin Ravindra	All-Rounder 	
1.80
6	Aravelly Rao	Wicket-Keeper 	
0.20
Punjab Kings
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Harshal Patel	All-Rounder 	
11.75
2	Rilee Rossouw	Batter 	
8.00
3	Chris Woakes	All-Rounder 	
4.20
4	Ashutosh Sharma	All-Rounder 	
0.20
5	Prince Choudhary	Bowler 	
0.20
6	Shashank Singh	All-Rounder 	
0.20
7	Tanay Thyagarajan	All-Rounder 	
0.20
8	Vishwapratap Singh	All-Rounder 	
0.20
Royal Challengers Bangalore
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Alzarri Joseph	Bowler 	
11.50
2	Yash Dayal	Bowler 	
5.00
3	Lockie Ferguson	Bowler 	
2.00
4	Tom Curran	All-Rounder 	
1.50
5	Swapnil Singh	All-Rounder 	
0.20
Gujarat Titans
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Spencer Johnson	Bowler 	
10.00
2	Shahrukh Khan	All-Rounder 	
7.40
3	Umesh Yadav	Bowler 	
5.80
4	Robin Minz	Wicket-Keeper 	
3.60
5	Sushant Mishra	Bowler 	
2.20
6	Kartik Tyagi	Bowler 	
0.60
7	Azmatullah Omarzai	All-Rounder 	
0.50
8	Manav Suthar	Bowler 	
0.20
Rajasthan Royals
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Rovman Powell	Batter 	
7.40
2	Shubham Dubey	Batter 	
5.80
3	Nandre Burger	Bowler 	
0.50
4	Tom Kohler-Cadmore	Wicket-Keeper 	
0.40
5	Abid Mushtaq	All-Rounder 	
0.20
Delhi Capitals
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Kumar Kushagra	Wicket-Keeper 	
7.20
2	Jhye Richardson	Bowler 	
5.00
3	Harry Brook	Batter 	
4.00
4	Sumit Kumar	All-Rounder 	
1.00
5	Shai Hope	Wicket-Keeper 	
0.75
6	Tristan Stubbs	Wicket-Keeper 	
0.50
7	Rasikh Dar	Bowler 	
0.20
8	Ricky Bhui	Wicket-Keeper 	
0.20
9	Swastik Chikara	Batter 	
0.20
Lucknow Super Giants
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Shivam Mavi	Bowler 	
6.40
2	Manimaran Siddharth	Bowler 	
2.40
3	David Willey	All-Rounder 	
2.00
4	Ashton Turner	Batter 	
1.00
5	Arshad Khan	All-Rounder 	
0.20
6	Arshin Kulkarni	All-Rounder 	
0.20
Mumbai Indians
NO.	Player Name 	Type 	Price Paid
(₹ Cr.) 
1	Gerald Coetzee	All-Rounder 	
5.00
2	Nuwan Thushara	Bowler 	
4.80
3	Dilshan Madushanka	Bowler 	
4.60
4	Mohammad Nabi	All-Rounder 	
1.50
5	Anshul Kamboj	All-Rounder 	
0.20
6	Naman Dhir	All-Rounder 	
0.20
7	Shivalik Sharma	All-Rounder 	
0.20
8	Shreyas Gopal	Bowler 	
0.20
```
"""

# Split text into lines
lines = text.splitlines()

team = ""
players_data = []

# Iterate over each line
for line in lines:
    if line.strip():  # Skip empty lines
        if "Knight Riders" in line or "Hyderabad" in line or "Punjab" in line or "Super Kings" in line or "Royals" in line or "Capitals" in line or "Bangalore" in line or "Titans" in line or "Indians" in line:
            # Set current team
            team = line.strip()
        elif line[0].isdigit():
            # If a line starts with a number, it's a new player entry
            parts = line.split('\t')
            player_name = parts[1]
            category = parts[2]
            # The next line should be the price
            price_index = lines.index(line) + 1
            price = lines[price_index].strip()

            # Add the player details to the list
            players_data.append([player_name, category, price, team])

# Write the data to CSV
with open('players_data.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Player Name", "Category", "Price (₹ Cr.)", "Team"])
    writer.writerows(players_data)

print("CSV created successfully!")

IndexError: list index out of range

In [27]:
import csv
from bs4 import BeautifulSoup

def convert_ipl_data_to_csv(html_content, output_file):
    """
    Convert IPL players data from HTML to CSV format
    
    Args:
        html_content (str): HTML content containing the IPL players data
        output_file (str): Name of the output CSV file
    """
    # Parse HTML content
    soup = BeautifulSoup(html_content, 'html.parser')
    
    # Find all team containers
    team_containers = soup.find_all('div', class_='AUipl_lst-wrp')
    
    # Prepare data for CSV
    players_data = []
    
    for team_container in team_containers:
        # Get team name
        team_name = team_container.find('h2', class_='AUipl_ttl').text.strip()
        
        # Find all player rows in the current team
        player_rows = team_container.find_all('tr', class_='AUipl_tbl-tr')
        
        # Skip header row
        for row in player_rows[1:]:  # Skip the header row
            columns = row.find_all('td')
            if columns:
                # Extract player name
                player_name = row.find('span', class_='AUipl_tbl-nm').text.strip()
                
                # Extract player category
                category = row.find('div', class_='AUipl_tbl-DXty').text.strip()
                
                # Extract price
                price = row.find('span', class_='AUipl_tx-CtRt').text.strip()
                
                # Add to players data
                players_data.append([
                    player_name,
                    team_name,
                    category,
                    price
                ])
    
    # Write to CSV file
    with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        # Write header
        writer.writerow(['Player', 'Team', 'Category', 'Price (₹ Cr.)'])
        # Write player data
        writer.writerows(players_data)

# Example usage
html_content = """

""" 

with open('sold_last_year.html','r') as f:
    html_content = f.read()


# Save to CSV
convert_ipl_data_to_csv(html_content, 'ipl_players.csv')